apiVersion: v1
kind: Namespace
metadata:
  name: nodeapp_dev
  labels:
    name: nodeapp_dev

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nodeapp_dev
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: jamesweb03:5000/nodeapp_dev:$BUILD_NUMBER
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        
        
---
apiVersion: v1
kind: Service
metadata:
  namespace: nodeapp_dev
  name: nodeapp-service
spec:
  selector:
    app: nodeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
